### ISSUE TITLE
Is there a way to use DB::transaction?

### ISSUE THREAD

**Issue by phaberest** [ziadoz/silex-capsule#4]
Hi!

I'm enjoying this package and I've been able to setup it properly without any issue.

I was wondering, anyway, if it was possible to use DB transactions like I'm used to with Laravel. I've tried all my bullets without results...

// EDIT
I see there is a `transaction()` method in `Illuminate\Database\Connection` which I was able to call after digging in the code trying and trying...

``` php
$this->app['db']->getConnection()->transaction(function () {
    //
});
```

This seems to work, it there anyway a better way of using it?

_NB: `$this->app['db']` is my Capsule instance_

Thanks in advance, have a nice day!

**Comment by ziadoz** [comment]
The example you've got there is how to use via the `Application` object. I guess you could also do this: 

```
use Illuminate\Database\Capsule\Manager as Capsule;

Capsule::connection()->transaction(function () {
    //...
});
```
